client_id = "55fc4b9bda2c09e3278bd014bf6447af"
name = "b2b-vies-approval"
application_url = "https://vies-approval-form.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "read_customers,write_customers,read_companies,write_companies,write_orders"
[auth]
redirect_urls = [ "https://vies-approval-form.onrender.com/api/auth" ]
[app_proxy]
url = "https://vies-approval-form.onrender.com/apps/invoice-request"
prefix = "apps"
subpath = "invoice-request"

[[webhooks.subscriptions]]
topics = [ "orders/create" ]
uri = "/webhooks/orders/create"